spring:
  datasource:
    url: jdbc:mysql://localhost:3308/shopping_online_incub
    username: root
    password: example
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    defer-datasource-initialization: true
    show-sql: true
  jackson:
    date-format: dd-MM-yyyy
    time-zone: Europe/Paris
logging:
  level:
    fr.insy2s.ecommerce: trace
    org.hibernate.SQL: debug
server:
  port: 9000


app:
  jwt:
    secret : 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970